/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Ajouter.AjouterClient;
import Ajouter.AjouterService;
import Ajouter.AjouterUtilisateur;
import Ajouter.EditerFacture;
import Connection.connection;
import static java.awt.AWTEventMulticaster.add;
import java.sql.ResultSetMetaData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static java.nio.file.Paths.get;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.UIManager.get;
import javax.swing.table.DefaultTableModel;
import liste.listeClient;
import liste.listeFacture;
import liste.listeService;
import liste.listeUtlisateur;

/**
 *
 * @author Acer i7
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Statement st;
    ResultSet rt;
    connection conn = new connection();
    public Accueil() {
        initComponents();
        JPanel [] pls= {ajS, liS,ajC, liC, edFact, liFact, ajU, liU};
        for(JPanel pl : pls){
        pl.setBackground(new Color(244,249,251));
        pl.addMouseListener(new MouseListener(){
            
            @Override
                 public void mouseClicked(MouseEvent e) { }

                 @Override
                 public void mousePressed(MouseEvent e) {
                 }

                 @Override
                 public void mouseReleased(MouseEvent e) {
                     
                 }
                 @Override
                 public void mouseEntered(MouseEvent e) {
                     pl.setBackground(new Color(47,143,208));}
                 
                 
                 @Override
                 public void mouseExited(MouseEvent e) {
                     pl.setBackground(new Color(244,249,251));}
            
            
        });
        
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jp9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jp8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel41 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        uad = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        Conteneur = new javax.swing.JPanel();
        pnlAccueil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlFacture = new javax.swing.JPanel();
        liFact = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        edFact = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlClient = new javax.swing.JPanel();
        ajC = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        liC = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlService = new javax.swing.JPanel();
        liS = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        ajS = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        labb = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        pnlUsers = new javax.swing.JPanel();
        ajU = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        labb1 = new javax.swing.JLabel();
        liU = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        jLabel10.setText("jLabel10");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ebsSlide.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel26.setText("jLabel26");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lAcartier.png"))); // NOI18N
        jLabel36.setText("jLabel36");

        jRadioButton1.setText("jRadioButton1");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("X");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(191, 191, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp1.setBackground(new java.awt.Color(181, 181, 249));
        jp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp1MouseClicked(evt);
            }
        });
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_home_35px.png"))); // NOI18N
        jp1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Accueil");
        jp1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jPanel2.add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 40));

        jp9.setBackground(new java.awt.Color(181, 181, 249));
        jp9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp9MouseClicked(evt);
            }
        });
        jp9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Utilisateurs");
        jp9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_conference_35px.png"))); // NOI18N
        jp9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel2.add(jp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 200, 40));

        jp2.setBackground(new java.awt.Color(181, 181, 249));
        jp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp2MouseClicked(evt);
            }
        });
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(191, 191, 249));
        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Factures");
        jp2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_purchase_order_35px.png"))); // NOI18N
        jp2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel2.add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 40));

        jp3.setBackground(new java.awt.Color(181, 181, 249));
        jp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp3MouseClicked(evt);
            }
        });
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Clients ");
        jp3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_user_groups_35px_1.png"))); // NOI18N
        jp3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel2.add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 40));

        jp8.setBackground(new java.awt.Color(181, 181, 249));
        jp8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp8MouseClicked(evt);
            }
        });
        jp8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Services");
        jp8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_document_35px.png"))); // NOI18N
        jp8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

        jPanel2.add(jp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 40));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/degrdé.PNG"))); // NOI18N
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 200, 410));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/degrdé.PNG"))); // NOI18N
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 270));

        jPanel9.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 600));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Wide Latin", 3, 32)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(134, 186, 134));
        jLabel41.setText("Ebs_Fact");
        jDesktopPane1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        jPanel11.setOpaque(false);
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("X");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 50, -1));

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));

        jButton1.setText("Se Déconnecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, -1, -1));

        uad.setBackground(new java.awt.Color(204, 255, 255));
        uad.setFont(new java.awt.Font("Sitka Banner", 1, 29)); // NOI18N
        uad.setForeground(new java.awt.Color(204, 255, 255));
        uad.setText("jooj");
        uad.setAutoscrolls(true);
        jPanel1.add(uad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, 30));

        jPanel9.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 100));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel42.setText("Copyright LeTuxx 2022- All right reserved");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 830, 40));

        Conteneur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        Conteneur.setOpaque(false);
        Conteneur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAccueil.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccueil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ebs_1.PNG"))); // NOI18N
        pnlAccueil.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 510, 350));

        jLabel4.setFont(new java.awt.Font("Swis721 Hv BT", 0, 48)); // NOI18N
        jLabel4.setText("La \"Bonne Semence\"");
        pnlAccueil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 520, 100));

        Conteneur.add(pnlAccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 550));

        pnlFacture.setBackground(new java.awt.Color(255, 255, 255));
        pnlFacture.setPreferredSize(new java.awt.Dimension(800, 550));
        pnlFacture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liFact.setBackground(new java.awt.Color(244, 249, 251));
        liFact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liFactMouseClicked(evt);
            }
        });
        liFact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel58.setText("Liste des Clients");
        liFact.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 285, -1, -1));

        jLabel59.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel59.setText("Liste des Factures");
        liFact.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/liste.png"))); // NOI18N
        liFact.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -40, 480, 330));

        pnlFacture.add(liFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 330, 450));

        edFact.setBackground(new java.awt.Color(244, 249, 251));
        edFact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edFactMouseClicked(evt);
            }
        });
        edFact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel61.setText("Editer une Facture");
        edFact.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/facture.PNG"))); // NOI18N
        edFact.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 440, 290));

        pnlFacture.add(edFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 330, 450));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel20.setText("FACTURES");
        pnlFacture.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 120, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fBlanc.png"))); // NOI18N
        pnlFacture.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        Conteneur.add(pnlFacture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pnlClient.setBackground(new java.awt.Color(255, 255, 255));
        pnlClient.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlClientComponentShown(evt);
            }
        });
        pnlClient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajC.setBackground(new java.awt.Color(244, 249, 251));
        ajC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajCMouseExited(evt);
            }
        });
        ajC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel16.setText("AJouter un client");
        ajC.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajClient.png"))); // NOI18N
        ajC.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 440, 290));

        pnlClient.add(ajC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 450));

        liC.setBackground(new java.awt.Color(244, 249, 251));
        liC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liCMouseClicked(evt);
            }
        });
        liC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel24.setText("Liste des Clients");
        liC.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 285, -1, -1));

        jLabel17.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel17.setText("Liste des clients");
        liC.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lClients.png"))); // NOI18N
        liC.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -40, 480, -1));

        pnlClient.add(liC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 330, 460));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fBlanc.png"))); // NOI18N
        pnlClient.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        Conteneur.add(pnlClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pnlService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liS.setBackground(new java.awt.Color(244, 249, 251));
        liS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liSMouseClicked(evt);
            }
        });
        liS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel52.setText("Liste des Clients");
        liS.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 285, -1, -1));

        jLabel53.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel53.setText("Liste des services rendus par l'imprimerie");
        liS.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/liste.png"))); // NOI18N
        label.setToolTipText("");
        liS.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, 480, -1));

        pnlService.add(liS, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 330, 450));

        ajS.setBackground(new java.awt.Color(244, 249, 251));
        ajS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajSMouseExited(evt);
            }
        });
        ajS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel55.setText("AJouter un Service");
        ajS.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        labb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/produit.PNG"))); // NOI18N
        ajS.add(labb, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -40, 440, 330));

        pnlService.add(ajS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 450));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fBlanc.png"))); // NOI18N
        pnlService.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 820, -1));

        Conteneur.add(pnlService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pnlUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajU.setBackground(new java.awt.Color(244, 249, 251));
        ajU.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ajU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajUMouseExited(evt);
            }
        });
        ajU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel56.setText("AJouter un utlisateurs");
        ajU.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        labb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/utlisateur.PNG"))); // NOI18N
        ajU.add(labb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 280));

        pnlUsers.add(ajU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 450));

        liU.setBackground(new java.awt.Color(244, 249, 251));
        liU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liUMouseClicked(evt);
            }
        });
        liU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel54.setText("Liste des Clients");
        liU.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 285, -1, -1));

        jLabel82.setFont(new java.awt.Font("Brandish", 0, 12)); // NOI18N
        jLabel82.setText("Liste des utilisateurs");
        liU.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/liste.png"))); // NOI18N
        label1.setToolTipText("");
        liU.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -70, 480, 350));

        pnlUsers.add(liU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 330, 450));

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fBlanc.png"))); // NOI18N
        pnlUsers.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 820, 670));

        Conteneur.add(pnlUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jPanel9.add(Conteneur, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 830, 560));

        getContentPane().add(jPanel9, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    private void jp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MouseClicked
        // TODO add your handling code here:
        pnlAccueil.setVisible(true);
        pnlFacture.setVisible(false);
        pnlClient.setVisible(false);
        pnlService.setVisible(false);
        pnlUsers.setVisible(false);
        jp1.setBackground(new Color(12,28,87));
        jp2.setBackground(new Color(181,181,249));
        jp3.setBackground(new Color(181,181,249));
        jp9.setBackground(new Color(181,181,249));
         jp8.setBackground(new Color(181,181,249));
    }//GEN-LAST:event_jp1MouseClicked

    private void jp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp2MouseClicked
        // TODO add your handling code here:
        pnlAccueil.setVisible(false);
        pnlFacture.setVisible(true);
        pnlClient.setVisible(false);
        pnlService.setVisible(false);
        
        jp1.setBackground(new Color(181,181,249));
        jp2.setBackground(new Color(12,28,87));
        jp3.setBackground(new Color(181,181,249));
        jp9.setBackground(new Color(181,181,249));
         jp8.setBackground(new Color(181,181,249));
    }//GEN-LAST:event_jp2MouseClicked

    private void jp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp3MouseClicked
        // TODO add your handling code here
        pnlAccueil.setVisible(false);
        pnlFacture.setVisible(false);
        pnlClient.setVisible(true);
        pnlService.setVisible(false);
        
        jp1.setBackground(new Color(181,181,249));
        jp3.setBackground(new Color(12,28,87));
        jp2.setBackground(new Color(181,181,249));
        jp9.setBackground(new Color(181,181,249));
         jp8.setBackground(new Color(181,181,249));
        
       
        
        
    }//GEN-LAST:event_jp3MouseClicked

    private void jp9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp9MouseClicked
        // TODO add your handling code here:
        pnlAccueil.setVisible(false);
        pnlFacture.setVisible(false);
        pnlClient.setVisible(false);
        pnlService.setVisible(false);
        pnlUsers.setVisible(true);
        
        jp1.setBackground(new Color(181,181,249));
        jp9.setBackground(new Color(12,28,87));
        jp3.setBackground(new Color(181,181,249));
        jp2.setBackground(new Color(181,181,249));
        jp8.setBackground(new Color(181,181,249));
    }//GEN-LAST:event_jp9MouseClicked

    private void ajCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajCMouseEntered
        // TODO add your handling code here:
        ajC.setBackground(new Color(201, 226, 255));
        
    }//GEN-LAST:event_ajCMouseEntered

    private void ajCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajCMouseExited
        // TODO add your handling code here:
        ajC.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_ajCMouseExited

    private void ajCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajCMouseClicked
        // TODO add your handling code here:
        AjouterClient f= new AjouterClient();
        
        f.setVisible(true);
        f.setLocation(418, 120);
        
    }//GEN-LAST:event_ajCMouseClicked

    private void liCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liCMouseClicked
        // TODO add your handling code here:

        new listeClient().setVisible(true);
         
       
    }//GEN-LAST:event_liCMouseClicked

    private void pnlClientComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlClientComponentShown
        // TODO add your handling code here:
//         String query = "select * from clients";
//        try {
//                st=conn.etablirconnection().createStatement();
//                rt=st.executeQuery(query);
//                ResultSetMetaData rsmd =rt.getMetaData();
//                DefaultTableModel model = (DefaultTableModel)tblClient.getModel();
//                
//                int cols = rsmd.getColumnCount();
//                String[] colName= new String[cols];
//                for(int i=1; i<cols;i++)
//                    colName[i]=rsmd.getColumnName(i+1);
//                
//                   model.setColumnIdentifiers(colName);
//                   String nom, telephone, email, adresse;
//                   while(rt.next()){
//                       nom = rt.getString(1);
//                       telephone = rt.getString(2);
//                       email= rt.getString(3);
//                       adresse= rt.getString(4);
//                       String[] row = {nom, telephone, email, adresse};
//                       model.addRow(row);
//                   }
//                    conn.etablirconnection().close();
//        } catch (Exception e) {
//        }
        
    }//GEN-LAST:event_pnlClientComponentShown

    private void liSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liSMouseClicked
        // TODO add your handling code here:
        new listeService().setVisible(true);
    }//GEN-LAST:event_liSMouseClicked

    private void ajSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajSMouseClicked
        // TODO add your handling code here:
        AjouterService a= new AjouterService();
        a.setVisible(true);
        a.setLocation(418, 120);
    }//GEN-LAST:event_ajSMouseClicked

    private void ajSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajSMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ajSMouseEntered

    private void ajSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajSMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ajSMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        pnlAccueil.setVisible(true);
        pnlFacture.setVisible(false);
        pnlClient.setVisible(false);
        pnlService.setVisible(false);
        pnlUsers.setVisible(false);
        
        jp1.setBackground(new Color(12,28,87));
        jp3.setBackground(new Color(181,181,249));
        jp2.setBackground(new Color(181,181,249));
        jp9.setBackground(new Color(181,181,249));
        
    }//GEN-LAST:event_formComponentShown

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseExited

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        //jPanel11.setOpaque(true);
        // jPanel11.setBackground(new Color(240,22,22));
         System.exit(0);
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        // TODO add your handling code here:
          jPanel11.setOpaque(true);
         // jPanel11.setBackground(new Color());
    }//GEN-LAST:event_jPanel11MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jp8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp8MouseClicked
        // TODO add your handling code here:
       
        pnlAccueil.setVisible(false);
        pnlFacture.setVisible(false);
        pnlClient.setVisible(false);

        pnlService.setVisible(true);
        pnlUsers.setVisible(false);
        
        jp1.setBackground(new Color(181,181,249));
        jp8.setBackground(new Color(12,28,87));
        jp3.setBackground(new Color(181,181,249));
        jp2.setBackground(new Color(181,181,249));
        jp9.setBackground(new Color(181,181,249));
    }//GEN-LAST:event_jp8MouseClicked

    private void ajUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajUMouseClicked
        // TODO add your handling code here:
        AjouterUtilisateur a = new AjouterUtilisateur();
        a.setVisible(true);
        a.setLocation(418,120);
    }//GEN-LAST:event_ajUMouseClicked

    private void ajUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajUMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ajUMouseEntered

    private void ajUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajUMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ajUMouseExited

    private void liUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liUMouseClicked
        // TODO add your handling code here:
        new listeUtlisateur().setVisible(true);
    }//GEN-LAST:event_liUMouseClicked

    private void edFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edFactMouseClicked
        // TODO add your handling code here:
        EditerFacture d =new EditerFacture();
        d.setVisible(true);
               d.setLocation(418, 120);
    }//GEN-LAST:event_edFactMouseClicked

    private void liFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liFactMouseClicked
        // TODO add your handling code here:
       listeFacture l= new listeFacture();
       l.setVisible(true);
       
    }//GEN-LAST:event_liFactMouseClicked
    public void SeXion(String ulix){
        uad.setText(ulix);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Conteneur;
    private javax.swing.JPanel ajC;
    private javax.swing.JPanel ajS;
    private javax.swing.JPanel ajU;
    private javax.swing.JPanel edFact;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp8;
    public javax.swing.JPanel jp9;
    private javax.swing.JLabel labb;
    private javax.swing.JLabel labb1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel liC;
    private javax.swing.JPanel liFact;
    private javax.swing.JPanel liS;
    private javax.swing.JPanel liU;
    private javax.swing.JPanel pnlAccueil;
    private javax.swing.JPanel pnlClient;
    private javax.swing.JPanel pnlFacture;
    private javax.swing.JPanel pnlService;
    private javax.swing.JPanel pnlUsers;
    private javax.swing.JLabel uad;
    // End of variables declaration//GEN-END:variables
}
