/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ajouter;

import Connection.connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer i7
 */
public class AjouterUtilisateur extends javax.swing.JFrame {

    connection con = new connection();
    Statement st;
    ResultSet rt;
    public AjouterUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Acp = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Nvp = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        jLabel1.setText("NOUVEAU UTILISATEUR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 26, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 662, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Identifiant");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 126, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mot de Passe");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 248, -1, 38));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Entrer Identifiant");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 245, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 662, 10));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        Acp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Acp.setText("password");
        Acp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AcpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AcpFocusLost(evt);
            }
        });
        Acp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcpActionPerformed(evt);
            }
        });
        getContentPane().add(Acp, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 250, 245, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Confirmer le mot de passe ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 352, -1, -1));

        Nvp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nvp.setText("password");
        Nvp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NvpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NvpFocusLost(evt);
            }
        });
        getContentPane().add(Nvp, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 347, 245, 38));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fBlanc.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if(jTextField1.getText().equals("Entrer Identifiant")){
            jTextField1.setText("");
            jTextField1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")){
            jTextField1.setText("Entrer Identifiant");
            jTextField1.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AjouterUtilisateur().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Acp.getText().equals(Nvp.getText())){
        
        
        String nom, pass;
        nom=jTextField1.getText();
        pass=Acp.getText();
        String query ="insert into utilisateur(n_user, mot_de_passe) values('"+nom+"','"+pass+"')" ;
       
            if( ("Entrer Identifiant".equals(nom)) || (Acp.getText().equals("password"))  ){
                if("Entrer Identifiant".equals(nom)){
                    JOptionPane.showMessageDialog(null,"Vous n'avez pas entrer d' Identifiant");
                }else{ JOptionPane.showMessageDialog(null,"Vous n'avez pas entrer de mot de passe");}
            }
            else{
            try{
                st = con.etablirconnection().createStatement();
                st.executeUpdate(query );
                 JOptionPane.showMessageDialog(null,"Informations ajoutées avec succes");
                 setVisible(false);
                 new AjouterUtilisateur().setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Cet Identifiant existe déja");
            }  } 
        
      }else{JOptionPane.showMessageDialog(null,"Confirmation incorrecte");}
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AcpActionPerformed

    private void AcpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AcpFocusGained
        // TODO add your handling code here:
        if(Acp.getText().equals("password")){
            Acp.setText("");
        }
    }//GEN-LAST:event_AcpFocusGained

    private void AcpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AcpFocusLost
        // TODO add your handling code here:
        if(Acp.getText().equals("")){
            Acp.setText("password");
        }
    }//GEN-LAST:event_AcpFocusLost

    private void NvpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NvpFocusGained
        // TODO add your handling code here:
        if(Nvp.getText().equals("password")){
            Nvp.setText("");
        }
    }//GEN-LAST:event_NvpFocusGained

    private void NvpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NvpFocusLost
        // TODO add your handling code here:
        if(Nvp.getText().equals("")){
            Nvp.setText("password");
        }
    }//GEN-LAST:event_NvpFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Acp;
    private javax.swing.JPasswordField Nvp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
