/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ajouter;

import Connection.connection;
import Facture.Facture1;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.TableModel;
import javax.swing.text.DateFormatter;
/**
 *
 * @author Acer i7
 */
public class EditerFacture extends javax.swing.JFrame {
    DefaultTableModel model;
     
    int prixTotal;
    int tva;
    int prixHT;
    String Date;
    String service; 
    String nomCl;
    String somm;
    
    /**
     * Creates new form EditerFacture
     */
    public EditerFacture() {
        
        initComponents();
        model = new DefaultTableModel(null,new String[]{"Quantité","Désignation","Prix Unit.","Prix Total"});
        
        
        jTable1.setModel(model);
        label_prixT.setText("Prix Total de la Facture: 0 FCFA");
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        jLabel8.setText(dFormat.format(date));
        
        RemplirCombe("clients",clientCombo);
        RemplirComboA();
        Boolean b = tvaB.isSelected();
        if(b==false){
        prixHT=prixTotal; }
        else{
        tva = prixTotal*18/100;
        prixHT = prixTotal-tva;} 
        Date = ""+date;
        nomCl=(String) clientCombo.getSelectedItem();
        somm = this.som.getText();
        service = (String) articleCombo.getSelectedItem();
        
        
        
    }
    public String getDate(){
        return jLabel8.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clientCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tvaB = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Imprimer = new javax.swing.JButton();
        label_prixT = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Visual = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        articleCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        qteSpin = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        som = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        jTable1.setPreferredSize(new java.awt.Dimension(100, 64));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 470, 100));

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel1.setText("Client");

        jLabel5.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel5.setText("TVA");

        jLabel7.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel7.setText("Date");

        tvaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvaBActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(tvaB)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvaB)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(clientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel5)))
                .addGap(13, 13, 13))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 670, 50));

        jButton1.setFont(new java.awt.Font("Valken", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_delete_35px.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 60, -1));

        jButton2.setFont(new java.awt.Font("Valken", 0, 18)); // NOI18N
        jButton2.setText("Tout effacer");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 150, 50));

        Imprimer.setFont(new java.awt.Font("Valken", 0, 18)); // NOI18N
        Imprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_print_35px_1.png"))); // NOI18N
        Imprimer.setText("Imprimer");
        Imprimer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Imprimer.setOpaque(false);
        Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 150, 40));

        label_prixT.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        label_prixT.setText("Prix Total");
        jPanel1.add(label_prixT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_close_30px.png"))); // NOI18N
        jButton6.setText("Fermer");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 150, 60));

        Visual.setFont(new java.awt.Font("Valken", 0, 18)); // NOI18N
        Visual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_pdf_2_35px.png"))); // NOI18N
        Visual.setText("Visualiser");
        Visual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Visual.setOpaque(false);
        Visual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualActionPerformed(evt);
            }
        });
        jPanel1.add(Visual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 150, 40));

        jLabel6.setFont(new java.awt.Font("Swis721 Lt BT", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FACTURE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 33));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 720, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 720, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 720, 10));

        jPanel4.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel2.setText("Article");

        jLabel3.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel3.setText("Quantité");

        qteSpin.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel4.setText("Prix Unitaire");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(articleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qteSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(articleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(qteSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 670, 40));

        jButton3.setFont(new java.awt.Font("Valken", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/icons8_plus_math_35px.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 40, -1));

        jLabel9.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel9.setText("Ecrivez le prix total en lettre :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        som.setColumns(20);
        som.setRows(5);
        jScrollPane2.setViewportView(som);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fBlanc.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tvaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvaBActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        
        if(r<0){
            JOptionPane.showMessageDialog(null, "Sélectionnez aucune ligne du table");
        }else{
            int prixR = (int) jTable1.getValueAt(r,3);
            prixTotal -= prixR;
            
            label_prixT.setText("Le prix total est : "+prixTotal+"FCFA");
            model.removeRow(r);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualActionPerformed
        // TODO add your handling code here:         
    }//GEN-LAST:event_VisualActionPerformed

    public Object[][] getTableData () {
    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
    Object[][] tableData = new Object[nRow][nCol];
    for (int i = 0 ; i < nRow ; i++)
        for (int j = 0 ; j < nCol ; j++)
            tableData[i][j] = (String) dtm.getValueAt(i,j);
    return tableData;
}
   
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
               String article = (String) articleCombo.getSelectedItem();
        int qte = (int) qteSpin.getValue();
        int prixU = Integer.parseInt(jTextField1.getText());
       
        int prixT = prixU*qte;
        if( (prixU>=0)){
            
                model.addRow(new Object[]{qte,article,prixU,prixT});
        prixTotal+=prixU;
        label_prixT.setText("Prix Total de la Facture: "+ prixTotal+" FCFA");
        model=(DefaultTableModel)jTable1.getModel();
        }else{
             JOptionPane.showMessageDialog(null, "Prix Unitaire: la donnée entrée n'est pas convenable");} 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Prix Unitaire: la donnée entrée n'est pas convenable");
        }
        
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        
  
        
    }//GEN-LAST:event_jPanel1ComponentShown

    public void effacerTable(JTable jt){
    DefaultTableModel model = (DefaultTableModel) jt.getModel();
    model.setRowCount(0);
}
     

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        effacerTable(jTable1);
        prixTotal=0;
        label_prixT.setText("Le prix Total est : "+prixTotal+" FCFA");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerActionPerformed
        // TODO add your handling code here:
        
        
         
    
    }//GEN-LAST:event_ImprimerActionPerformed
    public void RemplirCombe(String c, JComboBox cb){
              try {
            connection con = new connection();
            Statement st = con.etablirconnection().createStatement();
            String query="select nom from "+c+" order by nom";
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                   String nom= rs.getString("nom").toString();
                   cb.addItem(nom);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EditerFacture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void RemplirComboA(){
              try {
            connection con = new connection();
            Statement st = con.etablirconnection().createStatement();
            String query="select libelle from services order by libelle";
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                   String nom= rs.getString("libelle").toString();
                   articleCombo.addItem(nom);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EditerFacture.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditerFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditerFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditerFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditerFacture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               EditerFacture d = new EditerFacture();
               d.setVisible(true);
               d.setLocation(400, 120);
            }
        });
    }
    public String getClient(){
        return (String) clientCombo.getSelectedItem();
    }
    public JTable getTable(){
        return jTable1;
    }
    public String getArticle(){
        return (String) articleCombo.getSelectedItem();
    }
    public int getPrixT(){
        return prixTotal;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimer;
    private javax.swing.JButton Visual;
    private javax.swing.JComboBox<String> articleCombo;
    private javax.swing.JComboBox<String> clientCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_prixT;
    private javax.swing.JSpinner qteSpin;
    private javax.swing.JTextArea som;
    private javax.swing.JCheckBox tvaB;
    // End of variables declaration//GEN-END:variables
}
